blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/lucky-verma/awesome-creator-tools/discussions
    about: Have a question or want to discuss something? Start a discussion!
